blueprint:
  name: test
  domain: automation
  input:
    light:
      selector:
        target: {}
      name: Lamp
    motion:
      selector:
        device: {}
      name: Bewegingssensor
mode: restart
trigger:
  - type: motion
    platform: state
    target: !input motion
    domain: binary_sensor
action:
  - choose:
      - conditions:
          - type: is_motion
            platform: state
            target: !input motion
            domain: binary_sensor
        sequence:
          - service: light.turn_on
            metadata: {}
            data: {}
            target: !input light
      - conditions:
          - type: is_no_motion
            platform: state
            target: !input motion
            domain: binary_sensor
            for:
              hours: 0
              minutes: 2
              seconds: 0
        sequence:
          - service: light.turn_off
            target: !input light
            data: {}
