blueprint:
  name: Test Jeroen
  domain: automation
  input:
    light_target:
      name: Lamp
      selector:
        target:
          entity:
            domain: light
    motion:
      name: Motion
      selector:
        device:
          multiple: false
mode: restart
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input motion
action:
  - choose:
      - conditions:
          - type: is_motion
            condition: device
            entity_id: !input light
            domain: binary_sensor
        sequence:
          - service: light.turn_on
            metadata: {}
            data: {}
            target:
              device_id: 6c2550594d38e15ccbf9193c25d03c77
      - conditions:
          - type: is_no_motion
            condition: device
            entity_id: !input light
            domain: binary_sensor
            for:
              hours: 0
              minutes: 2
              seconds: 0
        sequence:
          - service: light.turn_off
            target:
              device_id: 6c2550594d38e15ccbf9193c25d03c77
            data: {}
